<?php

    $store = Mage::app()->getStore();

    $code  = $store->getCode();



    $_infoblock = Mage::getStoreConfig('porto_settings/contacts/infoblock', $code);

    $custom_block = Mage::getStoreConfig('porto_settings/contacts/customblock', $code);

?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<?php if($custom_block): ?>

<div class="row">

    <div class="col-sm-12">

        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($custom_block)->toHtml(); ?>

    </div>

</div>

<?php endif; ?>

<div class="row">

    <div class="col-sm-8">

<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">

    <h2 class="legend"><?php echo Mage::helper('contacts')->__('Deja') ?> <?php echo Mage::helper('contacts')->__(' un') ?> <b><?php echo Mage::helper('contacts')->__('Mensaje') ?></b></h2>

    <div class="row">

        <ul class="form-list col-sm-6">

            <li>

                <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>

                <div class="input-box">

                    <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />

                </div>

            </li>

            <li>

                <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>

                <div class="input-box">

                    <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />

                </div>

            </li>

            <li>

                <label for="telephone" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Celular') ?></label>

                <div class="input-box">

                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Celular') ?>" value="" class="input-text required-entry" type="text" />

                </div>

            </li>
            <li>

                <label for="ciudad" class="required"><em>*</em><em>*</em><?php echo Mage::helper('contacts')->__('Ciudad') ?></label>

                <div class="input-box">

                    <input name="ciudad" id="ciudad" title="<?php echo Mage::helper('contacts')->__('Celular') ?>" value="" class="input-text required-entry" type="text" />

                </div>

            </li>
            <li>

                <label for="empresa" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Empresa') ?></label>

                <div class="input-box">

                    <input name="empresa" id="empresa" title="<?php echo Mage::helper('contacts')->__('Empresa') ?>" value="" class="input-text required-entry" type="text" />

                </div>

            </li>
            <li>

                <label for="como"><?php echo Mage::helper('contacts')->__('Como se enteró de DI-ME LTDA.') ?></label>

                <div class="input-box">

                    <input name="como" id="como" title="<?php echo Mage::helper('contacts')->__('Como se enteró de DI-ME LTDA.') ?>" value="" class="input-text" type="text" />

                </div>

            </li>
            

        </ul>

        <ul class="form-list col-sm-6">

            <li class="captcha"><div class="g-recaptcha" data-sitekey="6Lc64EwUAAAAABH3hsnW55x90Am8KpwIwplTzeS7"></div></li>
            <li>

                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>

                <div class="input-box input-textarea">

                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3" placeholder="<?php echo Mage::helper('contacts')->__('Comment') ?>"></textarea>

                </div>

            </li>

            <li>

                <label for="acepto" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('') ?></label>

                <div class="input-box">
                    <div class="col-xs-2">
                        <input name="acepto" id="acepto" title="<?php echo Mage::helper('contacts')->__('Habeas Data') ?>" class="input-text required-entry" type="checkbox" />
                    </div>
                    <div class="col-xs-10">
                    Sus datos serán de uso exclusivo de DI-ME Ltda. Autorizo que envíen información de sus productos y servicios.
                    </div>

                </div>

            </li>

            <li>

                <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />

                <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>

            </li>

        </ul>

    </div>

</form>

<script type="text/javascript">

//<![CDATA[

    var contactForm = new VarienForm('contactForm', true);

//]]>

</script>
<script src='https://www.google.com/recaptcha/api.js'></script>

    </div>

    <div class="col-sm-4 contact-info">

        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Detalles ') ?> <b><?php echo Mage::helper('contacts')->__('de contacto') ?></b></h2>

        <?php

            echo $_infoblock;

        ?>

    </div>

</div>